### ISSUE TITLE
Typehead not firing src url?

### ISSUE THREAD

**Issue by CSWilson** [yuche/vue-strap#125]
Is typehead not working in v1.0.8?  It does not seem to be working on the demo site, nor in my test on CodePen: http://codepen.io/CSWApps/pen/reBZjB/

Or I may be missing a step?

**Comment by HelloGravity** [comment]
After seeing that the typeahead on the demo site does not work, I tried running the docs locally (`npm run docs`) and it worked. Apparently the code snippets on the docs site are not up to date, but the demo worked, so I was able to correct your codepen test: http://codepen.io/anon/pen/eZpQxW

There were 2 things that were wrong:
* The property `src` is now called `async`
* You forgot to add the github template in the data.
   I took the template from `docs/example/typeaheadDocs.vue` since the text in the code snippet is wrong. It should be:
        ```
<img width="18px" height="18px" :src="item.avatar_url"/> <span>{{item.login}}</span>
        ```

    and not: 
        ```
<img width="18px" height="18px" v-attr="src:avatar_url"/><span>{{login}}</span>
        ```

**Comment by CSWilson** [comment]
Awesome, thank you so much, I'm new to Vue and this was driving me crazy, I was looking at the example and everything looked correct to me, being new to Vue I did not know what was missing, thanks again.

**Comment by vesper8** [comment]
I don't understand the line template-name="typeahead-github-template"

I do not see typeahead-github-template anywhere.

Yet when I try to make my own async example and I put in a non-existent template name I get the message "Failed to resolve partial: template-name

How come yours works? What is this typeahead-github-template? Where is it? typeahead-github-template

**Comment by marceloch2** [comment]
@vesper8 same here, you had success on this?
