### ISSUE TITLE
I cant access the json object at the typeahead component

### ISSUE THREAD

**Issue by FerchoCarcho** [yuche/vue-strap#45]
having a Json Object  returned from the server, like 
[0 => 'email =>'me@test.com']] up to 10
how can I access it?
i tried
```

 <typeahead v-if="atrib.where=='sendto'"
                    key="items"
                    async="http://mysite.dev/search/"
                    placeholder="Busca Email"
                    template="{{customTemplate}}">
</typeahead>
```
```
 data: function () {
        return {
            customTemplate:'<span>{{items.email}}</span>',
```
but I get the 

TypeError: e[t.key] is undefined

**Comment by amanpatel** [comment]
More information is probably need to debug your problem. The biggest thing you probably are missing is to define a "on-hit" property that calls back a method in your component. Please read the docs here:

http://yuche.github.io/vue-strap/#typeahead

See the example that uses the google callback when an item is selected.

**Comment by FerchoCarcho** [comment]
thank you @amanpatel , I will take a look at it, and post the results :smile:

**Comment by kjfdebruin** [comment]
@FerchoCarcho Did you ever figure this out? From [here](http://yuche.github.io/vue-strap/#typeahead) it looks like we need to leave the "key" null if you return a json array directly. The documentation doesn't really tell us how "key" and "template" work together.

**Comment by kjfdebruin** [comment]
@FerchoCarcho OK, I figured it out. [Here](https://github.com/yuche/vue-strap/blob/master/src/Typeahead.vue#L17) is the actual typeahead template. It wasn't clear to me that the specified "key" is independent from the template. It now works for me - I return an array of JSON objects, I don't specify a "key", and then because the template iterates over `item in items`, then in the template I just refer to `{{item.value}}` (in my case each object has a "value" property).
