### ISSUE TITLE
can't required by webpack

### ISSUE THREAD

**Issue by leinue** [yuche/vue-strap#63]
nam install vue-strap --save-dev

require('vue-strap');

Error: Cannot find module "vue-strap"

then i use tag script,it works.
but i want to use require,how can i do?

**Comment by amanpatel** [comment]
Can't really help you further without more details on your setup. The best advice would be to follow an example project. Is any other require() working for you? for example, what happens when you do require('vue');

You can follow this vue example of how to setup webpack:
https://github.com/vuejs/vue-hackernews/

**Comment by leinue** [comment]
thank you,i have worked it out.
i use require('./node_modules/vue-strap/dist/vue-strap.js');
then it worked

**Comment by amanpatel** [comment]
@leinue Something is wrong with your setup. You shouldn't have to specify a full path like that. Check your webpack config and see if it has the following configuration (which tells to look under node_modules) for modules...

```js
  resolve: {
	'modulesDirectories': ['node_modules'],
  },
```
