### ISSUE TITLE
v-repeat not working on tabs

### ISSUE THREAD

**Issue by bflydesign** [yuche/vue-strap#76]
I am trying to create multiple tabs with the results of an api-call. When using v-repeat I am getting the correct nummer of objects in my array but there is no way I can access my properties to display them for e.g. the headers of my tabs.

I have 5 objects, so 5 tabs are created but neither of them has a header title.

When using a v-repeat on a simple list, it works perfectly.

[link to Stackoverflow with extra information](http://stackoverflow.com/questions/34395601/access-properties-in-v-repeat-over-array-from-objects-in-vue-js)

**Comment by amanpatel** [comment]
Wanted to ask this before we dwelve deep. Can you specify which version of vue-strap you are using? v1.0.x is not compatible with vue 0.12.x which is what you are using.

**Comment by bflydesign** [comment]
I understand. I am using the 0.12.x version as long as the 1.0 version is still in debug mode. I thought it might be a VueStrap issue so I skipped it and used the <ul class="nav nav-tabs"> from Bootstrap. Here I encouter the same problem. The tabs are created but I can't render the properties.

**Comment by amanpatel** [comment]
Vue v1 has been out for atleast couple of months. https://github.com/vuejs/vue/releases

You can still use vue-strap with vue 0.12.x, but you will have to install the previous branch:

```bash
$ npm install "vue-strap@v0.1.2"
```

Hope that helps.

**Comment by bflydesign** [comment]
@amanpatel I am the same guy from the question on stackoverflow. I have finally created a "working" fiddle except for the tabs. In this [fiddle](https://jsfiddle.net/bflydesign/079zjxed/) you'll see that the tabs are created but none of the values from 'categories' are rendered (e.g. in the tab-header).

When you remove the components-part in the vue model, the tabs are not longer created (logically) but I do get my values rendered in the input-field!

**Comment by amanpatel** [comment]
Hi, Thanks a lot for creating the fiddle. There are two issues:

1) A vue 0.12 issue: It seems that you can't use the scoped v-repeat item inside the component. So for example:
```html
<tab v-repeat="categories" header="{{text}}">
</tab>
```
will not work in Vue 0.12. If your project is small, I would advise you to upgrade to Vue 1.0.x.


2) To workaround (1), you could try this, but this is not supported by vue-strap 0.1.x. So again, the advice is to upgrade to Vue 1.0.x with vue-strap 1.0.x

```html
  <template v-repeat="cat in categories">
    <tab header="{{cat.text}}" v-class="active: !$index">
    </tab>
 </template>
```


(2) could probably be fixed by us, but there's much less motivation to work on issues related to 0.12.x If you think your project is too big and can't be migrated to 1.0.x I'll consider implementing a fix.


Hope it helps.

**Comment by bflydesign** [comment]
@amanpatel thx for looking into it! We do intend to migrate to 1.0.x soon! Keep on the good work! We enjoy working with VueStrap!
