### ISSUE TITLE
Panel doesn't show elements having v-if

### ISSUE THREAD

**Issue by marcotaubmann** [yuche/vue-strap#87]
A panel doesn't increase it's height when an inner element's v-if condition that was initially false turns true. Is this behavior intended or is this an issue?

https://jsfiddle.net/mhb3epfe/6/
html:
```html
<div id="app">
  <panel header="this panel works" :is-open="true">
    <input type="checkbox" v-model="initiallyChecked" /> show the conditional list
    <div v-if="initiallyChecked">
      conditional list:<ol><li>a</li><li>b</li><li>c</li></ol>
    </div>
  </panel>
  <panel header="this panel doesn't work" :is-open="true">
    <input type="checkbox" v-model="initiallyUnchecked" /> show the conditional list
    <div v-if="initiallyUnchecked">
      conditional list:<ol><li>a</li><li>b</li><li>c</li></ol>
    </div>
  </panel>
</div>
```
js:
```javascript
new Vue({
  el: '#app',
  data() {
    return {
      initiallyChecked: true,
      initiallyUnchecked: false
    }
  },
  components: {
    panel: VueStrap.panel
  }
})
```

I think it's because the [max-height property of the panels content](https://github.com/yuche/vue-strap/blob/master/src/Panel.vue#L49) is evaluated when the panel component is ready. When I remove that code line, the contend expands nicely for the initially disabled element, but the transition doesn't apply. Is there some method that doesn't break the transition?

This applies to v-show too.

**Comment by yuche** [comment]
I think add a resize listener to panel and re-evaluate the height may work. I will try to fix when I get a decent network condition. (I can’t access some website like Google or GitHub in my country)
 You can hack like this for a temporary solution: https://jsfiddle.net/mhb3epfe/8/




在 2016年1月11日 下午7:39:58, Marco (notifications@github.com) 写到:

A panel doesn't increase it's height when an inner element's v-if condition that was initially false turns true Is this behavior intended or is this an issue?

https://jsfiddlenet/mhb3epfe/6/
html:

  <panel header="this panel works" :is-open="true">
    <input type="checkbox" v-model="initiallyChecked" /> show the conditional list
    <div v-if="initiallyChecked">
      conditional list:<ol><li>a</li><li>b</li><li>c</li></ol>
    </div>
  </panel>
  <panel header="this panel doesn't work" :is-open="true">
    <input type="checkbox" v-model="initiallyUnchecked" /> show the conditional list
    <div v-if="initiallyUnchecked">
      conditional list:<ol><li>a</li><li>b</li><li>c</li></ol>
    </div>
  </panel>
js:

new Vue({
  el: '#app',
  data() {
    return {
      initiallyChecked: true,
      initiallyUnchecked: false
    }
  },
  components: {
    panel: VueStrappanel
  }
})
I think it's because the max-height property of the panels content is evaluated when the panel component is ready When I remove that code line, the contend expands nicely for the initially disabled element, but the transition doesn't apply Is there some method that doesn't break the transition?

This applies to v-show too

**Comment by sirlancelot** [comment]
I created patch #126 which calculates the max-height only when the panel is about to collapse instead of during the ready event. It may fix your problem.
